### ISSUE TITLE
intrinsicsExtrinsics2P

### ISSUE THREAD

**Issue by SharifaKar** [Coastal-Imaging-Research-Network/CIRN-Quantitative-Coastal-Imaging-Toolbox#29]
Hi Brittany/Kate,

I've grown to appreciate the toolbox more, as I learn more!

I just wanted to point out there may be a typo on line 17 for P:
![image](https://user-images.githubusercontent.com/60487340/104203384-ac6d4c80-53f1-11eb-9d92-89a193ae0a1d.png)

 I thought it was supposed to be 3 x 4, as indicated in line 77 of the code?

Sharifa

**Comment by burritobrittany** [comment]
Great catch. Thanks! Fixed!
